// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PS.Template.AccessData;

namespace PS.Template.AccessData.Migrations
{
    [DbContext(typeof(TemplateDbContext))]
    [Migration("20210923074606_prueba2")]
    partial class prueba2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PS.Template.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("DNI")
                        .HasMaxLength(8)
                        .HasColumnType("int");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NumeroCelular")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<int>("PartidoId")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("PlanId")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("TipoId")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.HasKey("ClienteId");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("PS.Template.Domain.Entities.HistoriaClinica", b =>
                {
                    b.Property<int>("HistoriaClinicaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Diagnostico")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TurnoId")
                        .HasMaxLength(255)
                        .HasColumnType("int");

                    b.HasKey("HistoriaClinicaId");

                    b.ToTable("HistoriaClinica");
                });

            modelBuilder.Entity("PS.Template.Domain.Entities.Partido", b =>
                {
                    b.Property<int>("PartidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PartidoId");

                    b.ToTable("Partido");

                    b.HasData(
                        new
                        {
                            PartidoId = 1,
                            Nombre = "Berazategui"
                        },
                        new
                        {
                            PartidoId = 2,
                            Nombre = "Florencio Varela"
                        },
                        new
                        {
                            PartidoId = 3,
                            Nombre = "Quilmes"
                        });
                });

            modelBuilder.Entity("PS.Template.Domain.Entities.Plan", b =>
                {
                    b.Property<int>("PlainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double>("Descuento")
                        .HasMaxLength(10)
                        .HasColumnType("float");

                    b.Property<string>("NombrePlan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("PrecioPlan")
                        .HasMaxLength(10)
                        .HasColumnType("float");

                    b.HasKey("PlainId");

                    b.ToTable("Plan");

                    b.HasData(
                        new
                        {
                            PlainId = 1,
                            Descripcion = "Descuento del 15% en especialidades comunes",
                            Descuento = 15.0,
                            NombrePlan = "Basico",
                            PrecioPlan = 1500.0
                        },
                        new
                        {
                            PlainId = 2,
                            Descripcion = "Descuento del 35% en todo tipo de especialidades",
                            Descuento = 35.0,
                            NombrePlan = "Premium",
                            PrecioPlan = 3500.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
